<a href="https://colab.research.google.com/github/Mlika-Gaith/Getting-Things-Done-with-Pytorch/blob/master/Pytorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Pytorch : 1# **Tensors**

What are tensors ?
Tensors are a specialized data structure that are very similar  to arrays and matrices. We use tensors to encode the inputs and outputs of a model.

In [1]:
!pip install torch
!pip install numpy

In [2]:
import torch
import numpy as np



1.   Initializing Tensors


In [4]:
# Directly from Data

data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
# From a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [13]:
# From another tensor

x_ones = torch.ones_like(x_data)
print (f"Ones Tensor: \n{x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print (f"Random Tensor: \n{x_rand} \n")

Ones Tensor: 
tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
tensor([[0.7735, 0.7991],
        [0.9283, 0.5254]]) 



In [25]:
# With random or constant values
shape = (1,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zero_tensor}")

Random Tensor: 
 tensor([[0.6209, 0.5115, 0.9587]]) 

Ones Tensor: 
 tensor([[1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.]])


2. Attributes of a Tensor

In [31]:
shape = (2,4)
tensor = torch.rand(shape)
print (f"The tesnor : {tensor}")
print(f"Datatype of tensor : {tensor.dtype}")
print(f"The shape of the tesnor : {tensor.shape}")
print(f"Tensor device : {tensor.device}")

The tesnor : tensor([[0.0403, 0.8753, 0.2173, 0.5986],
        [0.1259, 0.1294, 0.2091, 0.8020]])
Datatype of tensor : torch.float32
The shape of the tesnor : torch.Size([2, 4])
Tensor device : cpu


3. Operations on Tensors

In [32]:
# Move tensor to GPU
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

In [43]:
# Indexing and slicing
tensor = torch.rand(2,4)
print(f"The tensor : {tensor}")
print(f"First Row : {tensor[0]}")
print(f"First column : {tensor[:,0]}")
print(f"Last column : {tensor[...,-1]}")
tensor[:,1] = 0
print(tensor)

The tensor : tensor([[0.8003, 0.4440, 0.6243, 0.1952],
        [0.8713, 0.3102, 0.3245, 0.8150]])
First Row : tensor([0.8003, 0.4440, 0.6243, 0.1952])
First column : tensor([0.8003, 0.8713])
Last column : tensor([0.1952, 0.8150])
tensor([[0.8003, 0.0000, 0.6243, 0.1952],
        [0.8713, 0.0000, 0.3245, 0.8150]])


In [49]:
# Joining tensors
t1 = torch.cat([tensor,tensor,tensor],dim=0)
print(t1)

tensor([[0.8003, 0.0000, 0.6243, 0.1952],
        [0.8713, 0.0000, 0.3245, 0.8150],
        [0.8003, 0.0000, 0.6243, 0.1952],
        [0.8713, 0.0000, 0.3245, 0.8150],
        [0.8003, 0.0000, 0.6243, 0.1952],
        [0.8713, 0.0000, 0.3245, 0.8150]])


In [53]:
# Arithmetic operations : matrix multiplication
y1 = tensor @ tensor.T
print(f"The y1 tensor : {y1}")
y2 = tensor.matmul(tensor.T)
print(f"The y2 tensor : {y2}")
y3 = torch.rand_like(y1)
torch.matmul(tensor,tensor.T, out=y3)
print(f"The y3 tensor : {y3}")

The y1 tensor : tensor([[1.0682, 1.0589],
        [1.0589, 1.5287]])
The y2 tensor : tensor([[1.0682, 1.0589],
        [1.0589, 1.5287]])
The y3 tensor : tensor([[1.0682, 1.0589],
        [1.0589, 1.5287]])


In [54]:
# Arithmetic opertaions : element wise multiplication
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)
print(f"The z1 tensor : {z1}")
print(f"The z2 tensor : {z2}")
print(f"The z3 tensor : {z3}")

The z1 tensor : tensor([[0.6404, 0.0000, 0.3897, 0.0381],
        [0.7592, 0.0000, 0.1053, 0.6642]])
The z2 tensor : tensor([[0.6404, 0.0000, 0.3897, 0.0381],
        [0.7592, 0.0000, 0.1053, 0.6642]])
The z3 tensor : tensor([[0.6404, 0.0000, 0.3897, 0.0381],
        [0.7592, 0.0000, 0.1053, 0.6642]])


In [58]:
# Single element tensor
agg = tensor.sum()
print(f"the tensor : {agg}")
agg_item = agg.item()
print(agg_item, type(agg_item))

the tensor : 3.63051438331604
3.63051438331604 <class 'float'>


In [59]:
# In place operations
print(f"The tensor : {tensor}")
tensor.add_(5)
print(tensor)

The tensor : tensor([[0.8003, 0.0000, 0.6243, 0.1952],
        [0.8713, 0.0000, 0.3245, 0.8150]])
tensor([[5.8003, 5.0000, 5.6243, 5.1952],
        [5.8713, 5.0000, 5.3245, 5.8150]])


4. Bridge with numpy

In [62]:
# Tensor to numpy
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [63]:
# a change in the tensor reflects in the Numpy array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [66]:
# Numpy to tensor
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


In [68]:
# a change in the numpy array reflects in the tensor
np.add(n,5,out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([7., 7., 7., 7., 7.], dtype=torch.float64)
n: [7. 7. 7. 7. 7.]
